# Standards: 0.11
---

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted

- name: Restart ntpd
  service:
    name: ntpd
    state: restarted

- name: Merge audit rule files
  command: augenrules --load
  ignore_errors: yes

- name: Update grub
  command: "grub2-mkconfig -o /boot/grub2/grub.cfg"

- name: Restart server
  reboot:
       msg: "Reboot initiated by Ansible"
       connect_timeout: 5
       reboot_timeout: 600
       pre_reboot_delay: 0
       post_reboot_delay: 30
       test_command: whoami

