# Standards: 0.11
---

# 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)

- name: 4.1.1.2 Ensure system is disabled when audit logs are full
  replace:
    path: /etc/audit/auditd.conf
    regexp: 'max_log_file_action(.*)'
    replace: 'max_log_file_action = syslog'
  tags:
    - "4.1.1.2"
    - level-2
    - section-4
    - scored