# Standards: 0.11
---

# 5.4.5 Ensure default user shell timeout is 900 seconds or less (Scored)

- name: 5.4.5 Ensure default user shell timeout is 900 seconds or less (profile)
  lineinfile:
    dest: "/etc/profile"
    line: "TMOUT=600\n"
    insertbefore: BOF
  tags:
    - level-2
    - "5.4.5"
    - scored

- name: 5.4.5 Ensure default user shell timeout is 900 seconds or less (bash)
  lineinfile:
    dest: "/etc/bashrc"
    line: "TMOUT=600\n"
    insertbefore: BOF
  tags:
    - level-2
    - "5.4.5"
    - scored
