# Standards: 0.11
---

# 5.4.5 Ensure default user shell timeout is 900 seconds or less (Scored)

- name: 5.4.5 Ensure default user shell timeout is 900 seconds or less (profile)
  copy:
    dest: "/etc/profile"
    content: "TMOUT=600\n"
  tags:
    - level-2
    - "5.4.5"
    - scored

- name: 5.4.5 Ensure default user shell timeout is 900 seconds or less (bash)
  copy:
    dest: "/etc/bashrc"
    content: "TMOUT=600\n"
  tags:
    - level-2
    - "5.4.5"
    - scored
