# Standards: 0.11
---

# 1.1.18 Ensure sticky bit is set on all world-writable directories
  
  - name: 1.1.18 - Check if sticky bit is set on all world-writable directories
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
    register: ensure_sticky_bit
    changed_when: ensure_sticky_bit.stdout is not search('')
    tags:
      - level-1
      - section-1
      - "1.1.18"
      - scored
  
  - name: 1.1.18 Ensure sticky bit is set on all world-writable directories
    shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t 
    when: ensure_sticky_bit.changed  
    tags:
      - level-1
      - section-1
      - "1.1.18"
      - scored