# Standards: 0.11
---

# 1.5.3 Ensure prelink is disabled

- name: Check if prelink binary exists
  command: rpm -q prelink
  register: prelink
  ignore_errors: yes
  changed_when: prelink.stdout is not search('not installed')
  tags:
    - level-1
    - "1.5.3"
    - scored

- name: Restore prelinked binaries
  command: prelink -ua
  when: prelink.changed
  tags:
    - level-1
    - "1.5.3"
    - scored

- name: Ensure prelink is disabled
  yum:
    name: prelink
    state: absent
  tags:
    - level-1
    - "1.5.3"
    - scored
