# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP forwarding is disabled
  sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IPv6 forwarding is disabled
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 0
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IP forwarding is disabled
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IPv6 forwarding is disabled
  sysctl:
    name: net.ipv6.route.flush
    value: 1
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

