# Standards: 0.11
---

# 3.2.5 Ensure broadcast ICMP requests are ignored

- name: 3.2.5 - Ensure broadcast ICMP requests are ignored
  sysctl:
    ignoreerrors: yes
    name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: '1'
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.2.5"
    - scored

- name: 3.2.5 - Ensure broadcast ICMP requests are ignored by active kernel parameters
  sysctl:
    name: net.ipv4.route.flush 
    value: '1'
    state: present
    sysctl_set: yes
  tags:
      - level-1
      - section-3
      - "3.2.5"
      - scored

