# Standards: 0.11
---

# 3.2.6 Ensure bogus ICMP responses are ignored

- name: 3.2.6 - Ensure bogus ICMP responses are ignored
  sysctl:
    ignoreerrors: yes
    name: "net.ipv4.icmp_ignore_bogus_error_responses"
    value: '1'
    state: present
    sysctl_set: yes
  tags:
    - level-1
    - section-3
    - "3.2.6"
    - scored

- name: 3.2.6 - Ensure bogus ICMP responses are ignored by active kernel parameters
  sysctl:
    name: net.ipv4.route.flush 
    value: '1'
    state: present
    sysctl_set: yes
  tags:
      - level-1
      - section-3
      - "3.2.6"
      - scored
