# Standards: 0.11
---

  # 3.2.1 Ensure source routed packets are not accepted
  
  - name: 3.2.1 - Ensure source routed packets are not accepted
    sysctl:
      ignoreerrors: yes
      name: "{{ item }}"
      value: '0'
      state: present
      sysctl_set: yes
    with_items:
      - net.ipv4.conf.all.accept_source_route
      - net.ipv4.conf.default.accept_source_route
      - net.ipv6.conf.all.accept_source_route
      - net.ipv6.conf.default.accept_source_route
    tags:
      - level-1
      - section-3
      - "3.2.1"
      - scored
  
  - name: 3.2.1 - Ensure source routed packets are not accepted in active kernel parameters
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
      sysctl_set: yes
    with_items:
      - net.ipv4.route.flush
      - net.ipv6.route.flush
    tags:
      - level-1
      - section-3
      - "3.2.1"
      - scored