# Standards: 0.11
---

# 3.2.4 Ensure suspicious packets are logged

- name: 3.2.4 - Ensure suspicious packets are logged
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_set: yes
  with_items:
    - "net.ipv4.conf.all.log_martians"
    - "net.ipv4.conf.default.log_martians"
  tags:
    - level-1
    - section-3
    - "3.2.4"
    - scored

- name: 3.2.4 - Ensure source routed packets are not accepted in active kernel parameters
  sysctl:
    name: net.ipv4.route.flush 
    value: '1'
    state: present
    sysctl_set: yes
  tags:
      - level-1
      - section-3
      - "3.2.4"
      - scored