# Standards: 0.11
---

# 3.2.3 Ensure secure ICMP redirects are not accepted

- name: 3.2.3 - Ensure secure ICMP redirects are not accepted
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}"
    value: '0'
    state: present
    sysctl_set: yes
  with_items:
    - "net.ipv4.conf.all.secure_redirects"
    - "net.ipv4.conf.default.secure_redirects"
  tags:
    - level-1
    - section-3
    - "3.2.3"
    - scored

- name: 3.2.3 - Ensure source routed packets are not accepted in active kernel parameters
  sysctl:
    name: net.ipv4.route.flush 
    value: '1'
    state: present
    sysctl_set: yes
  tags:
      - level-1
      - section-3
      - "3.2.3"
      - scored

