# Standards: 0.11
---

 # 3.5.2.2 Ensure IPv6 loopback traffic is configured
  
  - name: 3.5.2.2 - Ensure IPv6 loopback traffic is configured
    iptables:
      action: append
      chain: INPUT
      in_interface: "lo"
      jump: ACCEPT
      state: present
    become: yes
    tags:
      - level-1
      - section-1
      - "3.5.2.2"
      - scored
      
  - name: 3.5.1.2 - Ensure loopback traffic is configured(-o lo)
    iptables:
      action: append
      chain: OUTPUT
      out_interface: "lo"
      jump: ACCEPT
      state: present
    become: yes
    tags:
      - level-1
      - section-3
      - "3.5.1.2"
      - scored
  
  - name: 3.5.1.2 - Ensure loopback traffic is configured(-i 127.0.0.1/8)
    iptables:
      action: append
      chain: INPUT
      source: 127.0.0.0/8
      jump: DROP
      state: present
    become: yes
    tags:
      - level-1
      - section-3
      - "3.5.1.2"
      - scored
  