# Standards: 0.11
---

# 3.5.2.1 Ensure IPv6 default deny firewall policy
  
  - name: 3.5.2.1 Ensure IPv6 default deny firewall policy
    iptables:
      ip_version: ipv6
      chain: "{{ item }}"
      policy: DROP
      state: present
    loop:
      - INPUT
      - OUTPUT
      - FORWARD
    tags:
      - level-1
      - section-1
      - "3.5.2.1"
      - scored
