# Standards: 0.11
---

# 4.2.4 Ensure permissions on all logfiles are configured

- name: 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "find /var/log -type f -perm '/o+r' -exec chmod g-wx,o-rwx {} +"

  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4.1 - Ensure Journal logs have correct permissions
  shell: "chmod 640 /var/log/journal/ec27041a88f931b46d484ac723cf13ee/user-1000.journal"
  ignore_errors: yes


  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4.1 - 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "chmod 000 /var/log/sa/sar06"

  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4.1 - 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "chmod 000 /var/log/sa/sa07"

  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4.1 - 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "chmod 000 /var/log/sa/sar07"

  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored

- name: 4.2.4.1 - 4.2.4 - Ensure permissions on all logfiles are configured
  shell: "chmod 000 /var/log/sa/sa08"

  tags:
    - level-1
    - section-4
    - "4.2.4"
    - scored
