# Standards: 0.11
---

# 5.3.2 Ensure lockout for failed password attempts is configured



- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_faillock.so - last)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_faillock.so
    module_arguments: 'authsucc
          audit
          deny=5
          unlock_time=900'
    state: after
  with_items:
    - system-auth
    - password-auth
  retries: 2
  delay: 2
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_faillock.so - after)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: "[default=die]"
    new_module_path: pam_faillock.so
    module_arguments: 'authfail
          audit
          deny=5
          unlock_time=900'
    state: after
  with_items:
    - system-auth
    - password-auth
  retries: 2
  delay: 2
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_unix.so)
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_control: '[success=1 default=bad]'
    module_arguments: ''
    state: updated
  with_items:
    - system-auth
    - password-auth
  retries: 2
  delay: 2
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored


- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_unix.so)
  replace:
    path:  /etc/pam.d/password-auth
    regexp: "{{ item.From }}"
    replace: "{{ item.To }}"
  with_items:
    - { From: '^\auth       [success=1 default=bad] pam_unix.so nullok try_first_pass', To: 'auth       [success=1 default=bad] pam_unix.so'}
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored

- name: 5.3.2 - Ensure lockout for failed password attempts is configured(pam_unix.so)
  replace:
    path:  /etc/pam.d/system-auth
    regexp: "{{ item.From }}"
    replace: "{{ item.To }}"
  with_items:
    - { From: '^\auth       [success=1 default=bad] pam_unix.so nullok try_first_pass', To: 'auth       [success=1 default=bad] pam_unix.so'}
  tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored