# Standards: 0.11
---

# 5.4.4 Ensure default user umask is 027 or more restrictive
#Optimize below into variables


- name: 5.4.4 - Ensure default user umask is 027 or more restrictive
  lineinfile:
    dest: "{{ i# 5.4.4 Ensure default user umask is 027 or more restrictive
#Optimize below into variables

- name: CIS 5.4.4 Ensure default user umask is 027 or more restrictive (/etc/profile 1/2)
  check_mode: false
  shell: tail -1 /etc/profile | grep "umask 027"
  register: umask_grep
  changed_when: umask_grep.rc != 0
  failed_when: false
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: CIS 5.4.4 Ensure default user umask is 027 or more restrictive (/etc/profile 2/2)
  shell: echo umask 027 >> /etc/profile
  when: umask_grep is changed
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: CIS 5.4.4 Ensure default user umask is 027 or more restrictive (/etc/bashrc 1/2)
  check_mode: false
  shell: tail -1 /etc/bashrc | grep "umask 027"
  register: umask_grep
  changed_when: umask_grep.rc != 0
  failed_when: false
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: CIS 5.4.4 Ensure default user umask is 027 or more restrictive (/etc/bashrc 2/2)
  shell: echo umask 027 >> /etc/bashrc
  when: umask_grep is changed
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored

- name: 5.4.4 - Ensure default user umask is 027 or more restrictive
  lineinfile:
    dest: "{{ item }}"
    regexp: '^(.*)umask 002(.*)$' 
    line: umask 027
    state: present
  loop:
    - /etc/profile.d/colorgrep.sh
    - /etc/profile.d/which2.sh
    - /etc/profile.d/less.sh
    - /etc/profile.d/colorls.sh
    - /etc/profile.d/256term.sh
    - /etc/profile.d/lang.sh
    - /etc/profile.d/vim.sh
    - /etc/profile.d/bash_completion.sh
  tags:
    - level-1
    - section-5
    - "5.4.4"
    - scored